name: Build and release binary libs

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Build libraries
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-2019]
    steps:
    - name: Install APT On Linux
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update -qq -y
        sudo apt-get install -qq -y libsdl2-dev flex bison libtinfo-dev patchelf
        curl -LO http://archive.ubuntu.com/ubuntu/pool/main/libf/libffi/libffi6_3.2.1-8_amd64.deb
        sudo dpkg -i libffi6_3.2.1-8_amd64.deb
    - name: Setup MSVC Paths
      if: matrix.os == 'windows-2019'
      uses: ilammy/msvc-dev-cmd@v1
    - uses: actions/checkout@v2
    - name: Run CMake
      run: |
        mkdir build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=release
    - name: Build Ubuntu
      if: matrix.os == 'ubuntu-latest'
      run: |
        cd build
        make -j 4
    - name: Build Windows
      if: matrix.os == 'windows-2019'
      run: |
        cd build
        MSBuild trusslibs.sln /p:Configuration=Release /p:Platform=x64
    - name: Zip Archive (linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        cd dist
        zip -r "../trusslibs_${{ matrix.os }}.zip" bin lib include
    - name: Zip Archive (windows)
      if: matrix.os == 'windows-2019'
      run: |
        cd dist
        7z a "../trusslibs_${{ matrix.os }}.zip" bin lib include
    - name: Publish Release
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        artifacts: trusslibs_${{ matrix.os }}.zip
        token: ${{ secrets.GITHUB_TOKEN }}
